autoInstallPeers: true
nodeLinker: hoisted

overrides:
  tar: "^7.5.7"
  js-yaml: "^3.15.0"
  "@types/node": "^22.0.0"
  "@types/minimatch": "~5.1.2"
  "@types/glob": "~8.1.0"
  "@types/react": "^17.0.0"
  cheerio: "1.2.0"

allowBuilds:
  core-js: true
  core-js-pure: true
  es5-ext: true
  highlight.js: true
