networks:
  default:
    external: true
    name: quay_default

services:
#  Not needed for local development
#  quay-service-tool-auth:
#    container_name: "quay-service-tool-auth"
#    image: jboss/keycloak
#    ports:
#      - '8081:8080'
#    environment:
#      - KEYCLOAK_USER=admin
#      - KEYCLOAK_PASSWORD=password

  quay-service-tool-api:
    container_name: "quay-service-tool-api"
    build:
      context: .
      target: backend-dev
    # these are mounted explicitly since mounting all of backend/ will clobber the
    # virtual environment created by `uv` during the image build
    volumes:
      - ./backend:/backend
    environment:
      ENV: development
      DEBUG: "True"
      PYTHONUNBUFFERED: "True"
      CONFIG_PATH: /backend/config
      IS_LOCAL: "True"

  quay-service-tool-client:
    container_name: "quay-service-tool-client"
    build:
      context: .
      target: frontend-dev
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/webpack.common.js:/frontend/webpack.common.js
      - ./frontend/webpack.dev.js:/frontend/webpack.dev.js
    ports:
      - '9000:9000'
    depends_on:
      - quay-service-tool-api
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=development
      - TARGET_URL=http://quay-service-tool-api:5000
