apiVersion: v1
kind: Template
metadata:
  name: quayio-service-tool
parameters:
- name: QUAY_SERVICE_TOOL_CONFIG_SECRET
  value: "quay-service-tool-config"
  required: true
- name: IMAGE
  value: "quay.io/app-sre/quayio-service-tool"
  required: true
- name: IMAGE_TAG
  value: ""
  required: true
- name: ACTIVE_DEADLINE_SECONDS
  value: "600"
  required: true
- name: CONFIG_MOUNT_PATH
  value: "/config"
  required: true
- name: QUAY_APP_COMPONENT_ANNOTATIONS_KEY
  value: "quay-service-tool-app-deployment"
  displayName: quay service tool app annotation
- name: QUAY_APP_COMPONENT_ANNOTATIONS_VALUE
  value: "update_me_when_secret_changes"
  displayName: quay service tool app annotation value
- name: REPLICAS
  value: "1"
  displayName: replicas for the deployment
- name: SERVICE_ANNOTATIONS
  value: "{}"
  displayName: Service annotations.
  description: Service annotations.
- name: QUAY_DISABLE_MIN_REPLICAS_CHECK
  displayName: Disable Minimum Replicas Check
  value: "ignore-check.kube-linter.io/minimum-three-replicas"
- name: QUAY_DISABLE_MIN_REPLICAS_REASON
  displayName: Reason for Disabling Minimum Replicas Check
  value: "Service tool only runs with one pod"
- name: QUAY_DISABLE_ANTI_AFFINITY_CHECK
  value: "ignore-check.kube-linter.io/no-anti-affinity"
  displayName: disable DVO check for anti-affinity
- name: QUAY_DISABLE_ANTI_AFFINITY_REASON
  value: "Service tool only ones with one replica"
  displayName: reason for disabling anti-affinity check
- name: QUAY_RESOURCES_REQUESTS_CPU
  value: "100m"
- name: QUAY_RESOURCES_REQUESTS_MEMORY
  value: "128Mi"
- name: QUAY_RESOURCES_LIMITS_MEMORY
  value: "256Mi"
- name: SERVICETOOL_LOGGING
  value: "syslog"
  displayName: Service tool logging method
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: quayio-service-tool
    labels:
      app: quayio-service-tool
    annotations:
      ${{QUAY_DISABLE_MIN_REPLICAS_CHECK}}: ${{QUAY_DISABLE_MIN_REPLICAS_REASON}}
      ${{QUAY_DISABLE_ANTI_AFFINITY_CHECK}}: ${{QUAY_DISABLE_ANTI_AFFINITY_REASON}}
  spec:
    replicas: ${{REPLICAS}}
    selector:
      matchLabels:
        app: quayio-service-tool
    template:
      metadata:
        labels:
          app: quayio-service-tool
        annotations:
          ${{QUAY_APP_COMPONENT_ANNOTATIONS_KEY}}: ${{QUAY_APP_COMPONENT_ANNOTATIONS_VALUE}}
      spec:
        volumes:
        - name: config
          secret:
            secretName: ${{QUAY_SERVICE_TOOL_CONFIG_SECRET}}
        containers:
        - name: quayio-service-tool
          image: ${IMAGE}:${IMAGE_TAG}
          command:
            - /conf/entrypoint.sh
          volumeMounts:
          - name: config
            mountPath: ${{CONFIG_MOUNT_PATH}}
            readOnly: true
          ports:
          - containerPort: 5000
          resources:
            limits:
              memory: ${{QUAY_RESOURCES_LIMITS_MEMORY}}
            requests:
              cpu: ${{QUAY_RESOURCES_REQUESTS_CPU}}
              memory: ${{QUAY_RESOURCES_REQUESTS_MEMORY}}
          env:
          - name: CONFIG_PATH
            value: ${{CONFIG_MOUNT_PATH}}
          - name: SERVICETOOL_LOGGING
            value: ${{SERVICETOOL_LOGGING}}
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 5000
            failureThreshold: 3
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 5000
            failureThreshold: 3
            timeoutSeconds: 30
            initialDelaySeconds: 30
            periodSeconds: 30
- apiVersion: v1
  kind: Service
  metadata:
    name: quayio-service-tool
    annotations: ${{SERVICE_ANNOTATIONS}}
    labels:
      run: quayio-service-tool
  spec:
    ports:
    - name: http
      port: 80
      targetPort: 5000
    selector:
      app: quayio-service-tool
    type: ClusterIP
