import os


ENVIRONMENT_CONFIG_KEYS = (
    "SPAM_DETECTION_STATE_DB_URI",
    "SPAM_DETECTION_STATE_DB_POOL_MIN",
    "SPAM_DETECTION_STATE_DB_POOL_MAX",
    "SPAM_DETECTION_STATE_DB_LOCK_CONNECTIONS",
    "SPAM_DETECTION_STATE_DB_SCHEMA",
    "SPAM_DETECTION_STATE_DB_CREATE_SCHEMA",
    "SPAM_DETECTION_S3_ENDPOINT_URL",
    "SPAM_DETECTION_S3_BUCKET",
    "SPAM_DETECTION_S3_PREFIX",
    "SPAM_DETECTION_S3_PROMOTED_KEY",
    "SPAM_DETECTION_S3_REGION",
    "SPAM_DETECTION_S3_ADDRESSING_STYLE",
    "SPAM_DETECTION_S3_VERIFY_TLS",
    "SPAM_DETECTION_S3_CREATE_BUCKET",
)


def apply_environment(config):
    for key in ENVIRONMENT_CONFIG_KEYS:
        value = os.environ.get(key)
        if value is not None:
            config[key] = value
    return config
